name: Build

on:
  push:
    tags:
      - '*'


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Install Workflow Dependencies
        run: python -m pip install twine build cibuildwheel==2.16.5

      - name: Build source
        run: python -m build --sdist
        # Doesn't matter which runner runs this, but only one should
        if: runner.os == 'Linux'

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      - name: Publish to PyPI
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
